[package]
name = "video-poker"
version = "0.1.0"
authors = ["Matthew Murphy <mashumafi@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.74"
arrayvec = "0.7.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"

[profile.release]
opt-level = "s"
