name: Build Video Poker
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup default nightly

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install wasm-opt
        run: npm i wasm-opt -g

      - run: yarn install && yarn build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: video-poker
          path: dist/*
